export const CHANGE_LOGIN_MODAL = 'CHANGE_LOGIN_MODAL';
export const CHANGE_AFTER_SIGNUP_MODAL = 'CHANGE_AFTER_SIGNUP_MODAL';
export const CHANGE_RECOVERY_PASS_MODAL = 'CHANGE_RECOVERY_PASS_MODAL';
export const CHANGE_AFTER_ACCEPT_MODAL = 'CHANGE_AFTER_ACCEPT_MODAL';
export const CHANGE_AVATAR_MODAL = 'CHANGE_AVATAR_MODAL';
export const CHANGE_BG_MODAL = 'CHANGE_BG_MODAL';
export const CHANGE_CONTACTS_MODAL = 'CHANGE_CONTACTS_MODAL';
export const CHANGE_SPORT_MODAL = 'CHANGE_SPORT_MODAL';
