export const ADD_EDUCATION = 'ADD_EDUCATION';
export const UPDATE_EDUCATION = 'UPDATE_EDUCATION';
export const CANCEL_EDIT_EDUCATION = 'CANCEL_EDIT_EDUCATION';
export const DELETE_EDUCATION = 'DELETE_EDUCATION';
export const EDIT_EDUCATION = 'EDIT_EDUCATION';
export const CHANGE_EDUCATION_ORDER = 'CHANGE_EDUCATION_ORDER';

export const SET_STATE = 'SET_STATE';

export const UPDATE_RESUME = 'UPDATE_RESUME';
export const UPDATE_USERCARD = 'UPDATE_USERCARD';

export const ADD_JOB = 'ADD_JOB';
export const UPDATE_JOB = 'UPDATE_JOB';
export const CANCEL_EDIT_JOB = 'CANCEL_EDIT_JOB';
export const DELETE_JOB = 'DELETE_JOB';
export const EDIT_JOB = 'EDIT_JOB';
export const CHANGE_JOB_ORDER = 'CHANGE_JOB_ORDER';
