export const CHANGE_ADD_KURS = 'CHANGE_ADD_KURS';
export const ADD_VIDEOKURS = 'ADD_VIDEOKURS';
export const SET_VIDEOKURS = 'SET_VIDEOKURS';
export const SET_SINGLE_KURS = 'SET_SINGLE_KURS';

export const CHANGE_ADD_UROK = 'CHANGE_ADD_UROK';
export const ADD_VIDEOUROK = 'ADD_VIDEOUROK';
export const SET_SINGLE_UROK = 'SET_SINGLE_UROK';
export const SET_VIDEOUROKI = 'SET_VIDEOUROKI';
