export const CHANGE_ADD_ALBUM_MODAL = 'CHANGE_ADD_ALBUM_MODAL';
export const CHANGE_ADD_PHOTO_MODAL = 'CHANGE_ADD_PHOTO_MODAL';

export const SET_ALBUMS = 'SET_ALBUMS';
export const SET_ALBUM = 'SET_ALBUM';
export const ADD_PHOTO = 'ADD_PHOTO';
