export const CHANGE_ADD_VIDEO_MODAL = 'CHANGE_ADD_VIDEO_MODAL';
export const ADD_NEW_VIDEO = 'ADD_NEW_VIDEO';
export const SET_VIDEOS = 'SET_VIDEOS';
export const SET_SINGLE = 'SET_SINGLE';
export const CHANGE_SINGLE_ABOUT = 'CHANGE_SINGLE_ABOUT';
export const SET_VIDEOS_MAIN = 'SET_VIDEOS_MAIN';
